// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateMaze(arg1:number,arg2:boolean):Promise<Array<any>>;

export function DeleteStartPoint(arg1:Array<any>):Promise<Array<any>>;

export function MazeExist():Promise<boolean>;

export function SetSPoint(arg1:Array<any>,arg2:number,arg3:number):Promise<Array<any>>;
