// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateMatrix(arg1) {
  return window['go']['main']['App']['CreateMatrix'](arg1);
}

export function MazeExist() {
  return window['go']['main']['App']['MazeExist']();
}
