// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateMaze(arg1, arg2) {
  return window['go']['main']['App']['CreateMaze'](arg1, arg2);
}

export function DeleteStartPoint(arg1) {
  return window['go']['main']['App']['DeleteStartPoint'](arg1);
}

export function MazeExist() {
  return window['go']['main']['App']['MazeExist']();
}

export function SetSPoint(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetSPoint'](arg1, arg2, arg3);
}
